apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ include "web.name" . }}
    chart: {{ include "web.chart" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "web.fullname" . }}
spec:
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaler.targetAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaler.targetAverageMemoryUtilization }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "web.fullname" . }}
