apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ include "web.name" . }}
    chart: {{ include "web.chart" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "web.fullname" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.webSecrets }}
  {{ $key }}: {{ $value | b64enc | quote}}
  {{- end -}}